config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[index] do
    resources :races, only: :index
  end

  resources :races, only: :show
end

app/models/race.rb
# frozen_string_literal: true

class Race < ApplicationRecord
  YAHOO_KEIBA_DOMAIN = 'https://keiba.yahoo.co.jp'

  belongs_to :event
  belongs_to :race_name, optional: true
  has_many :horse_results
  has_many :race_entries
  has_many :payouts

  enum grade: { g1: 1, g2: 2, g3: 3 }
  enum weather: %i[sunny cloudy rainy snowy]
  enum course_condition: %i[good good_to_soft soft heavy]
  enum course_type: %i[turf dirt turf_to_dirt]
  enum kind: %i[flat steeplechase]
  enum direction: %i[right left straight]
  enum circumference: %i[inner outer outer_to_inner]

  validates :ordinal, allow_nil: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, allow_nil: true, length: { minimum: 1 }
  validates :grade, allow_nil: true, inclusion: { in: Race.grades.keys }
  validates :distance, allow_nil: true, numericality: { only_integer: true, greater_than_or_equal_to: 1000 }
  validates :weather, allow_nil: true, inclusion: { in: Race.weathers.keys }
  validates :course_condition, allow_nil: true, inclusion: { in: Race.course_conditions.keys }

  before_validation :create_event

  delegate :short_name, to: :race_name

  def number
    id.slice(-2, 2).to_i
  end

  def yahoo_race_entry_url
    URI.join(YAHOO_KEIBA_DOMAIN, "/race/denma/#{id[2..-1]}/?page=2").to_s
  end

  def yahoo_race_result_time_url
    URI.join(YAHOO_KEIBA_DOMAIN, "/race/denma/#{id[2..-1]}/?page=3").to_s
  end

  def netkeiba_race_result_url
    "http://race.netkeiba.com/?pid=race&id=p20#{id}&mode=result".to_s
  end

  def course_name
    case id[2, 2]
    when '01' then '札幌'
    when '02' then '函館'
    when '03' then '福島'
    when '04' then '新潟'
    when '05' then '東京'
    when '06' then '中山'
    when '07' then '中京'
    when '08' then '京都'
    when '09' then '阪神'
    when '10' then '小倉'
    end
  end

  def crawl_entry
    EntryCrawler.new("http://race.netkeiba.com/?pid=race_old&id=p20#{id}").crawl.each do |entry|
      unless HorseResult.find_by(race: self, horse: entry.horse)
        entry.race = self
        entry.save!
      end
    end
  end

  def crawl_payout
    payouts.map(&:destroy!)
    PayoutCrawler.new("http://db.netkeiba.com/race/20#{id}/").crawl.each do |payout|
      payout.race = self
      payout.save!
    end
  end

  private

  def create_event
    self.event = Event.find_or_create_by!(id: id[2...10]) unless event_id
  end
end

app/controllers/races_controller.rb
# frozen_string_literal: true

class RacesController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @races = Race.where(event: @event).order(:id) || []
  end

  def show
    @race = Race.find(params[:id])
    @entries = HorseResult.includes(:jockey, :race, horse: %i[sire mare])
                          .where(race: @race)
                          .order(:horse_number)
    @gate_manager = GateManager.new(@entries.count)
    @races = @race.event.races.order(:id)
  end
end

app/helpers/races_helper.rb
# frozen_string_literal: true

module RacesHelper
end

app/views/races/index.html.erb
<h1><%= @event.name %></h1>

<div>
  <table>
    <tr>
      <thead>
        <th>レース</th>
        <th>レース名</th>
        <th>距離</th>
      </thead>
      <tbody>
        <% @races.each do |r| %>
          <tr>
            <td><%= r.number %>R</td>
            <td><%= r.distance %></td>
            <td><%= link_to(r.name, race_path(r.key)) %></td>
          </tr>
        <% end %>
      </tbody>
    </tr>
  </table>
</div>

app/views/races/show.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="#"><%= @race.event.name %></a>
  </div>
  <ul class="nav navbar-nav">
    <% @races.each do |race| %>
      <li class="<%= 'active' if race.id == params[:id] %>">
        <a href="<%= race_path(race) %>"><%= race.number %>R</a>
      </li>
    <% end %>
  </ul>
</nav>

<div>
  <h1><%= @race.name %></h1>
</div>

<div>
  <table id="entry" class="table">
    <thead>
      <tr>
        <th>枠番</th>
        <th>馬番</th>
        <th>馬名</th>
        <th>騎手</th>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
      <% @entries.each do |e| %>
        <tr>
          <% if @gate_manager.head_of_gate?(e.horse_number) %>
            <td class="gate <%= 'gate-' + e.gate_number.to_s %>"
                rowspan="<%= @gate_manager.gates[e.gate_number].length %>" >
              <%= e.gate_number %>
            </td>
          <% end %>
          <td class="gate"><%= e.horse_number %></td>
          <td><%= e.horse.name %></td>
          <td>
            <%= e.jockey.name %><br><%= e.jockey_weight %>
          </td>

          <% e.horse.latest_results(e.held_on).each do |hr| %>
            <td class="result">
              <div>
                <div><%= hr.held_on %></div>
                <div><%= hr.race.event.name %></div>
                <div><%= hr.short_name %></div>
                <div><%= hr.distance %></div>
                <div><%= (hr.race_time.to_i / 60).to_s + ':' + sprintf('%02d', hr.race_time.to_i % 60) + '.' + hr.race_time.to_s[-1] %></div>
                <div><%= hr.order_of_finish %>(<%= hr.popularity %>人)</div>
                <div><%= hr.jockey.name %> <%= hr.jockey_weight %></div>
                <div><%= hr.corner_position %> (<%= hr.last_3f %>)</div>
                <div><%= hr.horse_weight %> (<%= sprintf('%+d', hr.weight_diff) %>)</div>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>