config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[index] do
    resources :races, only: :index
  end

  resources :races, only: :show
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :races

  validates :held_on, presence: true, allow_nil: true
  validates :name,    presence: true, allow_nil: true

  def url
    "https://keiba.yahoo.co.jp/race/list/#{id}/"
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    today = Time.zone.today
    @year = params[:year]&.to_i || today.year
    @month = params[:month]&.to_i || today.month
    date = Date.new(@year, @month)
    @events = Event.where(held_on: month_period(date)).order(:held_on)
  end

  private

  def month_period(date)
    date.beginning_of_month..date.end_of_month
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/index.html.erb
<div>
  <%= form_tag events_path, method: :get do %>
    <%= select_tag :year, options_for_select((2000..@year).to_a.reverse, selected: @year) %> 年
    <%= select_tag :month, options_for_select((1..12), selected: @month) %> 月
    <%= submit_tag '移動' %>
  <% end %>
</div>
<div>
  <table>
    <thead>
      <tr>
        <th>開催日</th>
        <th>開催名</th>
      </tr>
    </thead>
    <% @events.each do |e| %>
      <tr>
        <td><%= link_to(e.held_on, event_races_path(e)) %></td>
        <td><%= e.name %></td>
      </tr>
    <% end %>
  </table>
</div>